### ISSUE TITLE
Input text affected by whitespace 

### ISSUE THREAD

**Issue by zygmuntszpak** [ArranWill/ask-guyala#1]
When typing "pizza" the website correctly detects "pizza boxes" but when typing "pizza " (note the extra white space) the item is no longer detected.

This can probably be fixed rather easily by trimming leading and trailing whitespace from the input string before parsing it.

**Comment by ArranWill** [comment]
Hi Zygmunt, thank you for bringing this issue to my attention. Valid input with leading or trailing whitespace is now accepted.
